version: "3.9"

networks:
  webserver:
    driver: bridge
    name: webserver
    external: false

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /data/${DB_NAME:-postgres}-${ENVIRONMENT}
    volumes:
      - ./docker/conf/${ENVIRONMENT}:/data/${DB_NAME:-postgres}/${ENVIRONMENT}
    # env_file:
    #   - ./.env
    ports:
      - "5432:5432"
    networks:
      - webserver
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webserver
    restart: unless-stopped

volumes:
  postgres:
  backend:
  redis_data:
