version: "3.9"

networks:
  webserver:
    driver: bridge
    name: webserver
    external: false
  web-network:
    driver: bridge

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - web-network
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - web-network
    environment:
      DB_HOST: postgres
      CACHES_HOST: redis
    restart: on-failure
    depends_on:
      - redis
      - postgres
    entrypoint: [ "/app/run.sh" ]
    


volumes:
  postgres_data:
  backend:
  redis_data:
