# Generated by Django 5.2.1 on 2025-05-18 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Token ID')),
                ('token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh'), ('sliding', 'Sliding')], max_length=10)),
                ('secret', models.CharField(blank=True, max_length=64)),
                ('usage', models.CharField(choices=[('api', 'API'), ('web', 'Web'), ('mobile', 'Mobile')], default='api', max_length=20)),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('iat', models.DateTimeField(auto_now_add=True)),
                ('exp', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.token')),
            ],
            options={
                'verbose_name': 'Bearer Token',
                'verbose_name_plural': 'Bearer Tokens',
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=60, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default-avatar.svg', null=True, upload_to='users/')),
                ('cover_image', models.ImageField(blank=True, default='default-cover.png', null=True, upload_to='users/')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, help_text='Primary refresh token for the user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.token')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'profiles',
            },
        ),
    ]
