# Generated by Django 5.2.1 on 2025-05-14 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the token', primary_key=True, serialize=False, unique=True, verbose_name='Key')),
                ('token', models.TextField(blank=True, help_text='Token Text for user auth with.', null=True)),
                ('iat', models.DateTimeField(auto_now_add=True, verbose_name='Issued At')),
                ('exp', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Time')),
                ('usage', models.CharField(choices=[('api', 'API'), ('web', 'Web'), ('mobile', 'Mobile')], default='api', help_text='Usage context for the token.', max_length=20)),
                ('token_type', models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh'), ('sliding', 'Sliding')], max_length=10)),
                ('secret', models.CharField(blank=True, help_text='A secure, random secret value for token validation.', max_length=64, null=True)),
                ('preferences', models.JSONField(blank=True, default=list, help_text='Additional preferences or metadata associated with the token.', null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_revoked', models.BooleanField(default=False)),
                ('desc', models.CharField(blank=True, max_length=64, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time the token was used.', null=True)),
                ('created_by', models.ForeignKey(help_text='The user who created this token (for audit purposes).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tokens', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Reference to the parent refresh token (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.token')),
            ],
            options={
                'verbose_name': 'Bearer Token',
                'verbose_name_plural': 'Bearer Tokens',
                'db_table': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, max_length=60, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default-avatar.svg', null=True, upload_to='users/')),
                ('cover_image', models.ImageField(blank=True, default='default-cover.png', null=True, upload_to='users/')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, help_text='The primary token for the user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_has', to='core.token')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Profile',
                'db_table': 'Profiles',
            },
        ),
    ]
