# Generated by Django 5.2.1 on 2025-05-19 15:00

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='stat',
            name='slug',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='slug',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False),
        ),
    ]
