# Generated by Django 5.2.1 on 2025-05-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        ('core', '0002_alter_profile_options_remove_profile_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='total_friends',
            new_name='total_workouts',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='total_records',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.profile'),
        ),
    ]
