# Generated by Django 5.2.1 on 2025-05-12 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_stats_stat'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseattendance',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseattendance',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='record',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='record',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='record',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By User'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='apis.workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('balance', 'Balance'), ('endurance', 'Endurance')], default='strength', max_length=50),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='ExerciseAttendance',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
