# Generated by Django 5.2.1 on 2025-05-19 15:02

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_exercise_slug_alter_stat_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stat',
            name='created_at',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stat',
            name='updated_at',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='updated_at',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
