name: Django Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      env:
        USE_SQLITE: True

      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose.yml"

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv 
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Run Django server (local run)
      env:
        DJANGO_SETTINGS_MODULE: "src.settings"  # Replace with your Django settings module
      run: |
        uv run manage.py migrate && uv run ./manage.py runserver
